function(qt_add_library target_name)
    set(target ${target_name})
    file(GLOB_RECURSE HEADER_FILES "*.h" "*.hpp")
    file(GLOB_RECURSE SOURCE_FILES "*.cpp" "*.cxx" "*.cc")
    add_library(${target} SHARED ${HEADER_FILES} ${SOURCE_FILES})
    set(libs ${ARGN})
    foreach(lib ${libs})
        target_link_libraries(${target} ${lib})
    endforeach()
endfunction()
